services:
  # REST API service
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    working_dir: /app
    command: node rest-api/server.js

  # GraphQL API service
  graphql-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    working_dir: /app
    command: node graphql-api/server.js

  # gRPC API service
  grpc-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "50051:50051"
    volumes:
      - .:/app
    working_dir: /app
    command: node grpc-api/server.js

  # Test client
  test-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - .:/app
      - ./results:/app/results
    working_dir: /app
    depends_on:
      - rest-api
      - graphql-api
      - grpc-api
    environment:
      - REST_URL=http://rest-api:3001
      - GRAPHQL_URL=http://graphql-api:3002/graphql
      - GRPC_URL=grpc-api:50051
    command: tail -f /dev/null